
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author omerkuf
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBedRoom = new javax.swing.JButton();
        btnBathroom = new javax.swing.JButton();
        btnKidRoom = new javax.swing.JButton();
        btnKitchen = new javax.swing.JButton();
        btnEntertainmentRoom = new javax.swing.JButton();
        btnLivingRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBedRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bedroom.jpeg"))); // NOI18N
        btnBedRoom.setText("jButton1");
        btnBedRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBedRoomActionPerformed(evt);
            }
        });

        btnBathroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bathroom.jpeg"))); // NOI18N
        btnBathroom.setText("jButton1");
        btnBathroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBathroomActionPerformed(evt);
            }
        });

        btnKidRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidRoom.jpeg"))); // NOI18N
        btnKidRoom.setText("jButton1");
        btnKidRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKidRoomActionPerformed(evt);
            }
        });

        btnKitchen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchen.jpeg"))); // NOI18N
        btnKitchen.setText("jButton1");
        btnKitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitchenActionPerformed(evt);
            }
        });

        btnEntertainmentRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/entertainmentRoom.jpeg"))); // NOI18N
        btnEntertainmentRoom.setText("jButton1");
        btnEntertainmentRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntertainmentRoomActionPerformed(evt);
            }
        });

        btnLivingRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livingroom.jpeg"))); // NOI18N
        btnLivingRoom.setText("jButton1");
        btnLivingRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivingRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBedRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBathroom, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLivingRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKidRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntertainmentRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnKitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBedRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLivingRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBathroom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKidRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntertainmentRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBedRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBedRoomActionPerformed
        
        
        BedRoomPage bedroom = new BedRoomPage();
        bedroom.setVisible(true);
        setVisible(false);
        
        
        
        
    }//GEN-LAST:event_btnBedRoomActionPerformed

    private void btnLivingRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivingRoomActionPerformed


        LivingRoomPage livingroom = new LivingRoomPage();
        livingroom.setVisible(true);
        setVisible(false);



    }//GEN-LAST:event_btnLivingRoomActionPerformed

    private void btnKitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitchenActionPerformed

       KitchenPage kitchen = new KitchenPage();
       
       kitchen.setVisible(true);
       setVisible(false);
       

    }//GEN-LAST:event_btnKitchenActionPerformed

    private void btnBathroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBathroomActionPerformed
        
        BathroomPage bathroom = new BathroomPage();
        bathroom.setVisible(true);
        setVisible(false);
        




    }//GEN-LAST:event_btnBathroomActionPerformed

    private void btnKidRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKidRoomActionPerformed
        
        KidRoomPage kidroom = new KidRoomPage();
        kidroom.setVisible(true);
        setVisible(false);
        
        



    }//GEN-LAST:event_btnKidRoomActionPerformed

    private void btnEntertainmentRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntertainmentRoomActionPerformed

        EntertainmentRoomPage entertainmentroom = new EntertainmentRoomPage();
        entertainmentroom.setVisible(true);
        setVisible(false);
        

    }//GEN-LAST:event_btnEntertainmentRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBathroom;
    private javax.swing.JButton btnBedRoom;
    private javax.swing.JButton btnEntertainmentRoom;
    private javax.swing.JButton btnKidRoom;
    private javax.swing.JButton btnKitchen;
    private javax.swing.JButton btnLivingRoom;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
